server:
  port: 7001

spring:
  thymeleaf:
    cache: false

  devtools:
    restart:
      additional-paths:
        - ife/
      exclude:
        - static/**
        - public/**
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      enabled: false

  security:
    filter:
      order: 10

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  main:
    allow-bean-definition-overriding: true